### ISSUE TITLE
Consider using Data.ByteString.Encodings.isAscii for checking ByteString asciiness

### ISSUE THREAD

**Issue by chessai** [snoyberg/ascii#8]
https://hackage.haskell.org/package/bytestring-encodings-0.2.0.2/docs/Data-ByteString-Encodings.html#v:isAscii

This function is about 8x faster than a call to `Data.ByteString.all (< 128)`, because instead of checking one `Word8` at a time, it can check eight `Word8`s at a time, using a cool bit twiddling optimisation. There is a test suite and benchmark suite to confirm that it both works and is that fast.

**Comment by snoyberg** [comment]
This library is not under active development, please see the README.

**Comment by chessai** [comment]
Oops, sorry about that.
